# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
# Your code here
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

insurance_df = pd.read_csv(url)
insurance_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
insurance_columns = insurance_df.columns
insurance_columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [3]:
def clean_column_names(df):
    df = df.rename(columns=lambda x: x.strip().lower().replace(' ', '_'))
    df = df.rename(columns={'st': 'state'})
    df = df.rename(columns={'customer': 'customer_id'})
    df = df.rename(columns={'education': 'education_level'})
    df = df.rename(columns={'monthly_premium_auto': 'monthly_auto_premium'})
    df = df.rename(columns={'number_of_open_complaints': 'open_complaints_count'})
    return df

insurance_df = clean_column_names(insurance_df)
insurance_df

,customer_id,state,gender,education_level,customer_lifetime_value,income,monthly_auto_premium,open_complaints_count,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [4]:
insurance_df['gender'].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [5]:
# Your code here
insurance_df['gender'] = insurance_df['gender'].str.strip().str.upper()  # Remove spaces & unify case
insurance_df['gender'] = insurance_df['gender'].replace({
    'FEMALE': 'F',
    'FEMAL': 'F',
    'MALE': 'M'
})

In [6]:
insurance_df['gender'].unique()

array([nan, 'F', 'M'], dtype=object)

In [7]:
insurance_df['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [8]:
state_map = {
    'AZ': 'Arizona',
    'Cali': 'California',
    'CALI': 'California',
    'WA': 'Washington',
    'NV':'Nevada',
    'OR':'Oregon'
}

insurance_df['state'] = insurance_df['state'].replace(state_map)
insurance_df['state'] = insurance_df['state'].str.strip().str.upper()
insurance_df['state'].unique()

array(['WASHINGTON', 'ARIZONA', 'NEVADA', 'CALIFORNIA', 'OREGON', nan],
      dtype=object)

In [9]:
insurance_df['education_level'].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [10]:
education_map = {
    'Bachelors': 'Bachelor',
}

insurance_df['education_level'] = insurance_df['education_level'].replace(education_map)
insurance_df['education_level'].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [11]:
insurance_df['customer_lifetime_value'] = insurance_df['customer_lifetime_value'].astype(str).str.replace('%', '')
insurance_df['customer_lifetime_value'] = pd.to_numeric(insurance_df['customer_lifetime_value'], errors='coerce')
insurance_df['customer_lifetime_value']

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: float64

In [12]:
insurance_df['vehicle_class'] = insurance_df['vehicle_class'].replace({
    'Sports Car': 'Luxury',
    'Luxury SUV': 'Luxury',
    'Luxury Car': 'Luxury'
})
insurance_df['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [13]:
# Your code here
insurance_df['customer_lifetime_value'] = pd.to_numeric(insurance_df['customer_lifetime_value'], errors='coerce')
insurance_df['customer_lifetime_value'].dtype

dtype('float64')

In [14]:
insurance_df['open_complaints_count'].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [15]:
insurance_df['open_complaints_count'] = insurance_df['open_complaints_count'].apply(
    lambda x: x.split('/')[1] if isinstance(x, str) and '/' in x else x
)
insurance_df['open_complaints_count'].unique()

array(['0', '2', '1', '3', '5', '4', nan], dtype=object)

In [16]:
insurance_df['open_complaints_count'] = pd.to_numeric(
    insurance_df['open_complaints_count'], errors='coerce').astype('Int64')
insurance_df['open_complaints_count'].dtype

Int64Dtype()

In [17]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              1071 non-null   object
 1   state                    1071 non-null   object
 2   gender                   954 non-null    object
 3   education_level          1071 non-null   object
 4   customer_lifetime_value  1068 non-null   float64
 5   income                   1071 non-null   float64
 6   monthly_auto_premium     1071 non-null   float64
 7   open_complaints_count    1071 non-null   Int64
 8   policy_type              1071 non-null   object
 9   vehicle_class            1071 non-null   object
 10  total_claim_amount       1071 non-null   float64
dtypes: Int64(1), float64(4), object(6)
memory usage: 348.5+ KB

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [18]:
insurance_df.isna().sum()

customer_id                2937
state                      2937
gender                     3054
education_level            2937
customer_lifetime_value    2940
income                     2937
monthly_auto_premium       2937
open_complaints_count      2937
policy_type                2937
vehicle_class              2937
total_claim_amount         2937
dtype: int64

In [19]:
last_rows = insurance_df.tail(2937)
last_rows.isna().sum()

customer_id                2937
state                      2937
gender                     2937
education_level            2937
customer_lifetime_value    2937
income                     2937
monthly_auto_premium       2937
open_complaints_count      2937
policy_type                2937
vehicle_class              2937
total_claim_amount         2937
dtype: int64

In [20]:
insurance_df = insurance_df.drop(insurance_df.tail(2937).index)
insurance_df

,customer_id,state,gender,education_level,customer_lifetime_value,income,monthly_auto_premium,open_complaints_count,policy_type,vehicle_class,total_claim_amount
0,RB50392,WASHINGTON,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,ARIZONA,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,NEVADA,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,CALIFORNIA,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,WASHINGTON,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,OREGON,M,Master,305955.03,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,CALIFORNIA,F,High School or Below,2031499.76,63209.0,102.0,2,Personal Auto,SUV,207.320041
1068,GS98873,ARIZONA,F,Bachelor,323912.47,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000
1069,CW49887,CALIFORNIA,F,Master,462680.11,79487.0,114.0,0,Special Auto,SUV,547.200000
1070,MY31220,CALIFORNIA,F,College,899704.02,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000

In [25]:
insurance_df.isna().sum()

customer_id                  0
state                        0
gender                     117
education_level              0
customer_lifetime_value      3
income                       0
monthly_auto_premium         0
open_complaints_count        0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [28]:
customer_gender = insurance_df["gender"].value_counts()
customer_gender

gender
F    502
M    452
Name: count, dtype: int64

In [ ]:
# To clean categorical data as is the Gender I will use the mode. In this case, there are more females (502), so we will add female in the null values.

In [29]:
insurance_df['gender'].mode()

0    F
Name: gender, dtype: object

In [31]:
mode_val = insurance_df["gender"].mode().iloc[0]
mode_val

'F'

In [33]:
insurance_df["gender"] = insurance_df["gender"].fillna(mode_val)

In [34]:
insurance_df.isna().sum()

customer_id                0
state                      0
gender                     0
education_level            0
customer_lifetime_value    3
income                     0
monthly_auto_premium       0
open_complaints_count      0
policy_type                0
vehicle_class              0
total_claim_amount         0
dtype: int64

In [39]:
median_val = insurance_df["customer_lifetime_value"].median()
median_val

588174.235

In [40]:
insurance_df["customer_lifetime_value"] = insurance_df["customer_lifetime_value"].fillna(median_val)

In [41]:
insurance_df.isna().sum()

customer_id                0
state                      0
gender                     0
education_level            0
customer_lifetime_value    0
income                     0
monthly_auto_premium       0
open_complaints_count      0
policy_type                0
vehicle_class              0
total_claim_amount         0
dtype: int64

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [44]:
insurance_df.duplicated().sum()

np.int64(0)

In [ ]:
# As there is non duplicated row i am going to leave it like this.

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [23]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [24]:
# Your code here